version: '3.1'

services:
  redis:
    image: redis
    container_name: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379"
    env_file:
      - .env
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: route_admin
      POSTGRES_USER: route_admin
    expose:
      - "5434" 
    ports:
      - "5434:5434"
    volumes:
      - ./backups:/home/backups
    command: -p 5434

  user:
    build: ./user/
    volumes:
      - ./user:/app/
    command: npm run dev
    ports:
      - "3004:3004"
    depends_on:
      - db
      - redis
  
  post:
    build: ./post-service/
    volumes:
      - ./post-service:/app/
    command: npm run dev
    ports:
      - "3003:3003"
    depends_on:
      - db
      - user